[package]
name = "forge-c64"
version = "0.1.0"
authors = ["Jonathan Nilsson <jonathan@voysys.se>"]
edition = "2018"

[dependencies]

[profile.dev]
lto = true
opt-level = 1

[profile.release]
lto = true